### ISSUE TITLE
Is it possible to define a recursive structure?

### ISSUE THREAD

**Issue by aoyama-val** [ksss/type_struct#7]
For example, binary tree:

```
require "type_struct"

Node = TypeStruct.new(
  left: Node,
  right: Node,
)
```

=>

```
node.rb:4:in `<main>': uninitialized constant Node (NameError)
```

**Comment by ksss** [comment]
@aoyama-val Sorry for late.
It is not possible yet.
And I have no idea about implementation.

**Comment by aoyama-val** [comment]
Thanks for reply.
That's a shame, but I know it's difficult, if possible. I really like the idea of this gem.
Please close the issue if you don't mind.

**Comment by ksss** [comment]
Thank you for a good idea.
